StartupEvents.registry('block', event => {
    // 1. 废土金属堆 (Scrap Pile)
    event.create('redshift:scrap_pile', "kubejs:slab")
        .displayName('Scrap Pile')
        .soundType('chain')
        .hardness(1.0)
        .resistance(3.0)
        .texture('minecraft:block/raw_iron_block')

    // 2. 引擎核心残骸 (Scrap Engine Core)
    event.create('redshift:scrap_engine')
        .displayName('Scrapped Engine Core')
        .soundType('lantern')
        .hardness(2.0)
        .resistance(6.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .texture('up', 'create:block/andesite_casing') 
        .texture('down', 'create:block/andesite_casing')
        .texture('north', 'create:block/gearbox')
        .texture('south', 'create:block/gearbox')
        .texture('east', 'create:block/andesite_casing')
        .texture('west', 'create:block/andesite_casing')
})